# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Release 생성 
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ steps.extract_version_name.outputs.version }} 
          release_name: ${{ steps.extract_version_name.outputs.version }}
      - name: Download releaseartifacts
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts
          path: release
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            release/*.zip
            release/*.tar.gz
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            checksum.txt
            release/*.zip
            release/*.tar.gz
